# Generated by Django 5.2.6 on 2025-10-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion_larga',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen_banner',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='texto_superpuesto',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
