# Generated by Django 5.2.6 on 2025-11-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_carrito_itemcarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='tracking_ling',
        ),
        migrations.AddField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(default='Cali', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.TextField(default='Por confirmar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='instrucciones_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo (Contra entrega)'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta Crédito/Débito'), ('pse', 'PSE'), ('mercado_pago', 'MercadoPago')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('express', ' Entrega Express (Hoy mismo)'), ('programada', ' Entrega Programada')], default='express', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ubicacion_actual',
            field=models.CharField(default='Preparando pedido', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='zona_entrega',
            field=models.CharField(choices=[('norte', 'Zona Norte'), ('sur', 'Zona Sur'), ('oriente', 'Zona Oriente'), ('occidente', 'Zona Occidente'), ('centro', 'Centro')], default='norte', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('preparacion', 'En preparación'), ('camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
