# Generated by Django 5.2.6 on 2025-11-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_remove_pedido_tracking_ling_pedido_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='hora_entrega',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
