# Generated by Django 5.2.6 on 2025-11-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_pedido_fecha_entrega_pedido_hora_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_transaccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('verificando', 'Verificando pago'), ('pagado', 'Pagado'), ('fallido', 'Pago fallido'), ('rechazado', 'Pago rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo (Contra entrega)'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata')], default='efectivo', max_length=20),
        ),
    ]
