# Generated by Django 5.2.6 on 2025-11-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_pedido_comprobante_pago_pedido_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='domiciliario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
