# Generated by Django 5.2.6 on 2025-11-20 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_pedido_domiciliario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='numero_transaccion',
        ),
    ]
