# Generated by Django 5.2.6 on 2025-11-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_remove_pedido_fecha_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='comprobante_pago',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_pago',
        ),
    ]
