# Generated by Django 5.2.6 on 2025-11-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_remove_pedido_comprobante_pago_remove_pedido_id_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente de pago')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo (Contra entrega)')], default='efectivo', max_length=20),
        ),
    ]
