# Generated by Django 5.2.6 on 2025-12-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_alter_pedido_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_promocion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_excesivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
