# Generated by Django 5.2.6 on 2026-01-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_producto_en_promocion_producto_precio_excesivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='keywords',
            field=models.TextField(blank=True, help_text='Palabras clave separadas por comas para mejorar la búsqueda del producto.'),
        ),
    ]
